### ISSUE TITLE
STILL No HUD

### ISSUE THREAD

**Issue by SLoW432** [Alf21/TTT2#314] opened 2019-03-17 23:22 UTC
i still not having any hud, even after the "fix", i tried to restart and reinstall but nothing works.

says tttc is creating some script errors
in console it says
[tttc] lua/classes/client/cl_hud.lua:106: attempt to index local 'hud' (a nil value)
  1. ClassesInfo - lua/classes/client/cl_hud.lua:106
   2. fn - lua/classes/client/cl_hud.lua:414
    3. unknown - lua/ulib/shared/hook.lua:109

is there something i can do? or until it got fixed the standard hud?
thank you for reading and your help

COLLECTION
https://steamcommunity.com/sharedfiles/filedetails/?id=1682622671

**Comment by Lxk3y** [comment] 2019-03-17 23:52
Install the Github version. I believe the wrong version has been uploaded to steam right now

**Comment by TimGoll** [comment] 2019-03-17 23:53
Yep, we're sorry but only alf is able to reupload the addon. For now you have to use the version from GitHub

**Comment by SLoW432** [comment] 2019-03-18 00:03
i need it in 16 hours from now, you guys think he will be uploading on steam until then? so i dont need to pull it from here ? ty for the answers

**Comment by TimGoll** [comment] 2019-03-18 00:07
no, use the GitHub version for now until we've come to know what the problem is. It seems like there's another problem, the steam version IS the right version. So we have to figure it out. But since it is a hobby for us and we all have to work tomorrow there is a high chance of not releasing an update tomorrow

**Comment by SLoW432** [comment] 2019-03-18 00:48
okay thank you, but how do i install it on the server, i put the files in the addons folder of my server but it dont work

**Comment by TimGoll** [comment] 2019-03-18 19:50
fixed in last release, please redownload from the workshop

**Closed by TimGoll** 2019-03-18 19:50 UTC
