### ISSUE TITLE
Bug with the notice of a role

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#54] opened 2018-11-10 19:47 UTC
Когда я определил труп survivalist, то мне написало в центре уведомление, мне выпала роль survivalist как в самом начале.

**Comment by Alf21** [comment] 2018-11-10 20:03
Do you mean that the role animated notification is shown while searching / identifying a player?

**Comment by Alf21** [comment] 2018-11-10 20:40
Fixed :)

**Comment by dok441** [comment] 2018-11-10 21:42
No, the problem is even after your updating if it of course isn't connected with a mistake and this problem not of a reshan yet in any way.

**Comment by dok441** [comment] 2018-11-10 21:43
Я когда шёл, мне написало выживший, я был предателем, кто-то определил труп видимо.

**Comment by Alf21** [comment] 2018-11-10 21:51
hmmm... I will try to repeat, but it should be fixed in the last ttt2-animation commit

**Comment by dok441** [comment] 2018-11-11 09:53
Теперь вообще, начинает писать разные роли даже в начале раунда, нужно исправлять =)

**Comment by Alf21** [comment] 2018-11-11 16:14
Did you update the ttt2-animations add-on? With the latest fixes, I was not able to reproduce this. It must be caused by your setup.

**Comment by Alf21** [comment] 2018-11-11 20:14
hmm... there is still an issue. It's caused on the networking. I will improve it to fix this issue and improve performance.

**Closed** 2018-11-13 21:49 UTC
Labels: bug, important
