### ISSUE TITLE
INFECTED ROLE BUG

### ISSUE THREAD

**Issue by dok441** [Alf21/TTT2#36] opened 2018-11-05 15:07 UTC
If the infected, kills someone, the weapon is not issued to him and his servant goes without weapons, apparently the weapon is registered, which is not. Also, if GL.infected kills someone, and until the emergence of Ml.infected, kill the Main, then reborn Ml.infected innocent, although I should die.

**Comment by SchokoShampoo** [comment] 2018-11-05 16:58
Do you mean that the infected loses his knife after he killed someone?

**Comment by dok441** [comment] 2018-11-06 13:03
No, he doesn't have a gun, which is written in the files, you need to fix it.

**Comment by SchokoShampoo** [comment] 2018-11-06 13:59
In which files it is written that he gets a gun?

**Comment by SchokoShampoo** [comment] 2018-11-06 14:00
The main infected has the same equipment as an innocent.
The other infected only get a knife

**Comment by dok441** [comment] 2018-11-06 14:01
That's the translator translated it, I mean, weapons, anything. There are registered weapon_ttt_tigers such weapons it does not issue.

**Comment by SchokoShampoo** [comment] 2018-11-06 14:02
thats the bloddy knife which is marked as neccessary in the workshop for the infected
https://steamcommunity.com/workshop/filedetails/?id=380972923

**Comment by dok441** [comment] 2018-11-06 15:53
Well, then there is a bug with the death of HL infected and the appearance of Ml.infected as innocent, though they have just been to die, after the death of the host.

**Comment by SchokoShampoo** [comment] 2018-11-06 16:24
First: What do you mean with HL and MI
Second: It is planned that if the Main-Infected is killed all other Infected are being killed

**Comment by dok441** [comment] 2018-11-06 16:34
HL - Zombie leader.  MI - are his subordinates.

**Comment by SchokoShampoo** [comment] 2018-11-06 16:41
What do you mean they appear as innocent?

**Comment by dok441** [comment] 2018-11-06 18:38
If you kill them, and before they revive you, they kill who you killed, they are reborn not infected, but innocent and can play, even if they were traitors.

**Comment by SchokoShampoo** [comment] 2018-11-07 11:36
So if the HL is killed all MIs are killed too
If a Traitor is turned into an Infected and then killed he becomes an innocent
Is that the situation?

**Comment by dok441** [comment] 2018-11-07 12:01
If HL. kills someone, and the person died, it should take 1-5 seconds to respawn in an infiltrated, but during that time kill HL.an infected, revived person becomes innocent.

**Comment by SchokoShampoo** [comment] 2018-11-07 12:13
Ok, i understand i will look what i can do and answer soon

**Comment by SchokoShampoo** [comment] 2018-11-07 20:56
I can't reproduce this on my server :( 
For me if I'm the HL.Infected and i kill someone. The Person is dead for 3 seconds. If I die in these 3 seconds then he just respawns as nothing has happend

**Comment by dok441** [comment] 2018-11-07 21:28
I often see (around 2-3 times) this happen, especially when I was a Main Infected, maybe this happens rarely. Will be better to add some «tester» which will check is the Main Infected alive or not before respawning someone as Infected.

**Comment by SchokoShampoo** [comment] 2018-11-08 07:44
There is check implemented
The role is set after the 3 seconds and before nothing special happens.

**Comment by SchokoShampoo** [comment] 2018-11-08 07:45
Also could you translate directly to German instead of English, maybe then Alf and I can understand you better :/

**Comment by dok441** [comment] 2018-11-08 10:37
Ich sehe häufig (rund 2-3mal) das geschieht besonders, als ich eine Angesteckte Hauptsache war, vielleicht geschieht das selten. Wird besser sein, um einen «Prüfer» hinzuzufügen, der überprüfen wird, ist die Hauptsache Angesteckt lebendig oder nicht vor dem Wiederlaichen von jemandem als Angesteckt.

**Comment by Alf21** [comment] 2018-11-08 10:42
Alright we need to implement a check, maybe we missed that

**Comment by SchokoShampoo** [comment] 2018-11-08 15:56
Check implemented.
Is it fixed now?

**Comment by Alf21** [comment] 2018-11-10 21:37
You know :D Don‘t forget to close it :) ty for your reports!

**Closed** 2018-11-11 19:17 UTC
Labels: Fixed (?)
